### ISSUE TITLE
Running Eval on DMR results in division by zero error.

### ISSUE THREAD

**Issue by RSTZZZ** [McGill-NLP/weblinx#12]
For  https://github.com/McGill-NLP/weblinx/blob/436b9eaa03a825e28f3c5236e791c9a083dfb871/modeling/dmr/processing.py#L367,

 the default should be `data-webtasks-id` instead of `data-weblinx-id` to run:

```
def build_records_for_single_demo(
    demo,
    format_intent_input,
      ##max_neg_per_turn=None,
    random_state=None,
    uid_key="data-webtasks-id",
    only_allow_valid_uid=True,
    group_by_turn=False,
)
```

With  `data-weblinx-id`, 
https://github.com/McGill-NLP/weblinx/blob/436b9eaa03a825e28f3c5236e791c9a083dfb871/modeling/dmr/processing.py#L325,
will be an empty list -->total records for the demo will be 0.

**Comment by xhluca** [comment]
Fixed here: https://github.com/McGill-NLP/weblinx/commit/bab7b731cd6cb51051a2b6ce175d26f8ae7e501f
