### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by frt03** [McGill-NLP/weblinx#16]
Dear authors,

Thank you for releasing an impressive benchmark! I'm willing to use this for another of my projects, but I cannot find a license file. I guess your code is published under Apache License 2.0, as far as I read `setup.py`, but could you add one if possible?

https://github.com/McGill-NLP/weblinx/blob/6942e00dba5dd2fc060f6e4f288b068b5cc48cee/setup.py#L36

**Comment by xhluca** [comment]
Thanks! I indeed forgot to include a license. I have added it to the repo. The Apache 2.0 license only applies to the code on this repo; the data (hosted on huggingface) will have a different license.
