### ISSUE TITLE
Fix colab to include how to download splits.json

### ISSUE THREAD

**Issue by xhluca** [McGill-NLP/weblinx#40]
right now it assumes the splits.json exists but it doesn't show how to download splits.json: https://huggingface.co/datasets/McGill-NLP/WebLINX-full/blob/main/splits.json

**Comment by JJstin** [comment]
<img width="1260" alt="Screenshot 2024-09-25 at 8 37 24 PM" src="https://github.com/user-attachments/assets/7bf9c80c-ca07-4563-b64e-30a528c12cf8">
I tried to download it with this button, and it works for me. Is this the "download" you are referring to?

**Comment by xhluca** [comment]
no, this issue is specific to the colab notebook we used to go over the weblinx tutorial.
