### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement weblinx (from versions: none) ERROR: No matching distribution found for weblinx

### ISSUE THREAD

**Issue by Winsome-A** [McGill-NLP/weblinx#41]
ERROR: Could not find a version that satisfies the requirement weblink (from versions: none)
ERROR: No matching distribution found for Weblinx
 I tried to pip install your Python library, but it seems to be unavailable?? Why? 
Everyone cannot pip install it forever?
I am so sad. Wuwuwuwuuw

**Comment by xhluca** [comment]
You have a typo, it's `pip install weblinx` not `pip install weblink`
